spring.application.name=CB


spring.jpa.hibernate.ddl-auto=update
spring.jpa.open.in-view=false

springdoc.swagger-ui-path=/docs


spring.datasource.url = ${DB_URL}
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password= ${DB_PASSWORD}


spring.jwt.secret= ${SPRING_JWT_SECRET}
spring.jwt.expiration= ${SPRING.JWT.EXPIRATION:900000}

supabase.url= ${SUPABASE_URL}
supabase.service-role-key = ${SUPABASE_SERVICE_ROLE_KEY}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

